# Generated by Django 5.1.13 on 2025-10-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
