# Generated by Django 5.2.7 on 2025-11-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('compras', '0003_categoriaproveedor_proveedor_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProveedor',
            new_name='Categoria',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.categoria'),
        ),
    ]
