# Generated by Django 5.2.7 on 2025-11-05 13:58

import django.core.validators
import django.db.models.deletion
import compras.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('compras', '0004_rename_categoriaproveedor_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.ForeignKey(default=1, help_text='Seleccione una categoría', on_delete=django.db.models.deletion.PROTECT, to='compras.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='certificacion',
            field=models.FileField(blank=True, null=True, upload_to='certificaciones/', validators=[compras.validators.validate_pdf_file], verbose_name='Certificación (PDF)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_entrega',
            field=models.CharField(blank=True, help_text='Días en que el proveedor realiza entregas (ej: Lunes, Miércoles).', max_length=50, verbose_name='Días de entrega'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='Direccion no especificada', max_length=255, verbose_name='Dirección de entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='sin@email.com', max_length=254, validators=[compras.validators.validate_email_format], verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=0, default='10.000', max_digits=12, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Monto mínimo de pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(default='21145334-6', max_length=12, unique=True, validators=[compras.validators.validate_rut], verbose_name='RUT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tiempo_entrega',
            field=models.PositiveIntegerField(default=1, verbose_name='Tiempo de entrega (días)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(default='ad', max_length=100, verbose_name='Contacto principal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='9888888', max_length=20, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Total')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles de la compra (opcional).', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedor')),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
