# Generated by Django 5.2.8 on 2025-11-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('compras', '0005_proveedor_categoria_proveedor_certificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del insumo')),
                ('valor_clp', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Valor en CLP')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='compras.proveedor')),
            ],
        ),
    ]
