# Generated by Django 5.2.8 on 2025-11-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('compras', '0006_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='correo_contacto',
            field=models.EmailField(default='add@add.cl', max_length=254, verbose_name='Correo de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_entrega',
            field=models.CharField(default='adf', max_length=255, verbose_name='Dirección de entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='compras', to='compras.insumo'),
        ),
    ]
