# Generated by Django - data migration to add proveedor_nombre values for existing compras
from django.db import migrations, models
import django.db.models.deletion


def populate_proveedor_nombre(apps, schema_editor):
    Compra = apps.get_model('compras', 'Compra')
    Proveedor = apps.get_model('compras', 'Proveedor')
    for compra in Compra.objects.all():
        try:
            if compra.proveedor:
                compra.proveedor_nombre = compra.proveedor.nombre
            else:
                # mantener lo que ya haya o dejar en blanco
                compra.proveedor_nombre = compra.proveedor_nombre or ''
            compra.save()
        except Exception:
            # ignorar errores en la migración de datos para no bloquear
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_change_compra_proveedor_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='proveedor_nombre',
            field=models.CharField(default='', max_length=200, blank=True, help_text='Nombre del proveedor al momento de la compra para conservar historial'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_proveedor_nombre, reverse_code=migrations.RunPython.noop),
    ]
