# Generated by Django 5.2.8 on 2025-11-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_add_proveedor_nombre_and_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor_nombre',
            field=models.CharField(blank=True, help_text='Nombre del proveedor al momento de la compra para conservar historial', max_length=200, verbose_name='Nombre proveedor (histórico)'),
        ),
    ]
