# Generated by Django 5.2.8 on 2025-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_rename_proveedor_nombre_to_nombre_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='insumos',
        ),
        migrations.AlterField(
            model_name='compra',
            name='nombre_proveedor',
            field=models.CharField(blank=True, help_text='Nombre del proveedor en el momento de la compra', max_length=200, verbose_name='Nombre proveedor (histórico)'),
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
    ]
