# Generated by Django 5.2.7 on 2025-11-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_compra_nombre_proveedor'),
        ('compras', '0012_remove_compra_insumos_alter_compra_nombre_proveedor_and_more'),
    ]

    operations = [
    ]
