# Generated by Django 5.2.7 on 2025-11-23 02:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_merge_20251106_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tiempo_entrega',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Tiempo de entrega (días)'),
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('monto_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('RECHAZADO', 'Rechazado'), ('APROBADO', 'Aprobado'), ('CERRADA', 'Cerrada')], default='EN_ESPERA', max_length=20, verbose_name='Estado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='compras.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=200, verbose_name='Insumo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='Subtotal')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
            ],
        ),
    ]
