# Generated by Django 5.2.7 on 2025-11-23 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_proveedor_tiempo_entrega_ordencompra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('MEDIO', 'Medio'), ('MALO', 'Malo'), ('MUY_MALO', 'Muy malo')], max_length=20, verbose_name='Calidad')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripción breve')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='compras.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
