# Generated by Django 5.2.7 on 2025-11-23 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_evaluacionproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='IVA (19%)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='neto',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
