# Generated by Django 5.2.7 on 2025-11-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_ordencompra_iva_ordencompra_neto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden', to='compras.proveedor'),
            preserve_default=False,
        ),
    ]
