# Generated by Django 5.2.7 on 2025-11-23 04:09

import compras.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_remove_ordencompra_proveedor_detalleorden_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de anulación'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_anulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, validators=[compras.validators.validate_phone], verbose_name='Teléfono'),
        ),
    ]
