# Generated by Django 5.2.7 on 2025-11-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_ordencompra_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='insumo',
            field=models.CharField(blank=True, help_text='Nombre del insumo (histórico o manual)', max_length=200, verbose_name='Insumo (Texto)'),
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del insumo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='compras.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='insumo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.insumo', verbose_name='Insumo (Catálogo)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='insumos',
            field=models.ManyToManyField(blank=True, help_text='Insumos que ofrece este proveedor', related_name='proveedores', to='compras.insumo'),
        ),
    ]
