# Generated by Django 5.2.7 on 2025-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_alter_detalleorden_insumo_insumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='agregar_contacto_secundario',
            field=models.BooleanField(default=False, verbose_name='¿Agregar contacto secundario?'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_secundario_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido contacto secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_secundario_direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección contacto secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_secundario_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email contacto secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_secundario_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre contacto secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_secundario_rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT contacto secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_secundario_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono contacto secundario'),
        ),
    ]
