# Generated by Django 5.2.7 on 2025-12-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_proveedor_agregar_contacto_secundario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría principal del proveedor (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.categoria'),
        ),
    ]
