# Generated by Django 5.2.7 on 2025-12-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_alter_proveedor_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'Orden Creada'), ('ORDER_APPROVED', 'Orden Aprobada'), ('ORDER_REJECTED', 'Orden Rechazada'), ('ORDER_CLOSED', 'Orden Cerrada')], max_length=20, verbose_name='Tipo')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('COMPRAS', 'Compras'), ('INVENTARIO', 'Inventario'), ('BODEGA', 'Bodega'), ('FINANZAS', 'Finanzas')], max_length=20, verbose_name='Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
