# Generated by Django 5.2.7 on 2025-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_alter_ordencompra_estado_notification_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
