# Generated by Django 5.2.7 on 2025-12-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0023_alter_ordencompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='EN_ESPERA', max_length=20, verbose_name='Estado'),
        ),
    ]
