# Generated by Django 5.2.7 on 2025-12-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0024_ordencompra_updated_at_alter_ordencompra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='EN_ESPERA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría principal del proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.categoria'),
        ),
    ]
