# Generated by Django 5.2.7 on 2025-12-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0025_alter_ordencompra_estado_alter_proveedor_categoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='zwt_categoria',
        ),
        migrations.AlterModelTable(
            name='compra',
            table='zwt_compra',
        ),
        migrations.AlterModelTable(
            name='detalleorden',
            table='zwt_detalle_orden',
        ),
        migrations.AlterModelTable(
            name='evaluacionproveedor',
            table='zwt_evaluacion_proveedor',
        ),
        migrations.AlterModelTable(
            name='insumo',
            table='zwt_insumo',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='zwt_notification',
        ),
        migrations.AlterModelTable(
            name='ordencompra',
            table='zwt_orden_compra',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='zwt_proveedor',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='zwt_user_profile',
        ),
    ]
